---

- hosts: db
  remote_user: vagrant
  become: yes
  tasks:
  - name: install mysql server
    apt: name=mysql-server state=installed
  - name: enable and assure started
    service: name=mysql state=started enabled=yes
