---
- name: install mysql
  apt: name=mysql-server state=installed update_cache=yes

- name: install mysql python client
  apt: name=python-mysqldb state=installed

- name: ensure started and enabled on boot
  service: name=mysql state=started enabled=yes

- name: correct config with bind ip
  template: src=my.cnf.j2 dest=/etc/mysql/my.cnf owner=mysql
  notify: restart mysql

- name: create database
  mysql_db: name={{dbname}}
- name: create user
  mysql_user: name={{dbuser}} password={{dbpass}} priv='*.*:ALL' state=present
